#include "database.h"
#include <QApplication>
#include <QMainWindow>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDesktopServices>
#include <QUrl>
#include <QFileInfo>
#include <QStringConverter>
#include <QTabWidget>
#include <QTableWidget>
#include <QHeaderView>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFormLayout>
#include <QLineEdit>
#include <QTextEdit>
#include <QComboBox>
#include <QDoubleSpinBox>
#include <QDateEdit>
#include <QPushButton>
#include <QMessageBox>
#include <QFileDialog>
#include <QFile>
#include <QTextStream>
#include <QLabel>
#include <QFrame>
#include <QSplitter>
#include <QStandardPaths>
#include <QDir>
#include <QSqlRecord>
#include <QStatusBar>
#include <QGroupBox>
#include <QInputDialog>
#include <QScrollArea>
#include <QDateTime>
#include <functional>
#include <cmath>

static qint64 cents(double d){return static_cast<qint64>(std::llround(d*100.0));}
static QPushButton* action(const QString &label,const std::function<void()> &fn,QHBoxLayout *layout){auto b=new QPushButton(label);layout->addWidget(b);QObject::connect(b,&QPushButton::clicked,fn);return b;}
static QLineEdit* input(const QString &value=""){auto *w=new QLineEdit;w->setText(value);return w;}
static QDoubleSpinBox* number(double value=0,bool signedValue=false,int decimals=2){auto*w=new QDoubleSpinBox;w->setRange(signedValue?-100000000:0,100000000);w->setDecimals(decimals);w->setValue(value);w->setGroupSeparatorShown(true);return w;}
static QComboBox* lookup(Database &db,const QString &sql,const QVariantList &args={}){auto*w=new QComboBox;auto q=db.query(sql,args);while(q.next())w->addItem(q.value(1).toString(),q.value(0));return w;}
static void selectId(QComboBox*w,int id){for(int i=0;i<w->count();i++)if(w->itemData(i).toInt()==id){w->setCurrentIndex(i);return;}}
static bool showForm(QWidget *parent,const QString &title,QFormLayout *form,QDialog &dialog){Q_UNUSED(parent);dialog.setWindowTitle(title);dialog.setMinimumWidth(440);auto *v=new QVBoxLayout(&dialog);v->addLayout(form);auto *buttons=new QDialogButtonBox(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);v->addWidget(buttons);QObject::connect(buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);QObject::connect(buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);return dialog.exec()==QDialog::Accepted;}

class Japan365Window : public QMainWindow {
    Database db;
    QTabWidget *tabs=nullptr;
    QVector<QTableWidget*> tables;
    QVector<QLineEdit*> searches;
    QVector<QComboBox*> filters;
    QStringList names={"Dashboard","Products","Warehouses","Stock Transfer","Stock Adjustment","Expenses","Payment Accounts","Reports"};
    QLabel *summary=nullptr;
public:
    Japan365Window(){db.initialize();setWindowTitle("Japan 365 POS");resize(1340,820);tabs=new QTabWidget;tables.resize(8);searches.resize(8);filters.resize(8);setCentralWidget(tabs);
        for(int i=0;i<names.size();++i){auto *page=new QWidget;tabs->addTab(page,names[i]);if(i==0)setupDashboard(page);else if(i==7)setupReports(page);else setupTable(page,i);}
        connect(tabs,&QTabWidget::currentChanged,this,[this](int i){refresh(i);});statusBar()->showMessage("Local SQLite database: " + db.path());refresh(0);
        setStyleSheet("QMainWindow{background:#f4f7fb;} QTabWidget::pane{border:1px solid #dce5ef;background:white;} QTabBar::tab{padding:12px 16px;background:#e6edf5;color:#233349;} QTabBar::tab:selected{background:#154c83;color:white;} QPushButton{padding:8px 13px;background:#155d95;color:white;border:0;border-radius:5px;} QPushButton:hover{background:#0f4877;} QLineEdit,QComboBox,QDoubleSpinBox,QDateEdit{padding:6px;border:1px solid #cad5e1;border-radius:4px;} QTableWidget{gridline-color:#e6edf5;alternate-background-color:#f5f9fd;} QHeaderView::section{background:#e9f1fa;padding:9px;border:0;font-weight:600;} QLabel#headline{font-size:22px;font-weight:700;color:#163d67;} ");
    }
private:
    void guard(const std::function<void()>&fn){try{fn();refresh(tabs->currentIndex());}catch(const std::exception &e){QMessageBox::warning(this,"Unable to complete",QString::fromUtf8(e.what()));}}
    QTableWidget* makeTable(QWidget *parent,QVBoxLayout *v,int i){Q_UNUSED(parent);auto*t=new QTableWidget;t->setAlternatingRowColors(true);t->setSelectionBehavior(QAbstractItemView::SelectRows);t->setSelectionMode(QAbstractItemView::SingleSelection);t->setEditTriggers(QAbstractItemView::NoEditTriggers);t->verticalHeader()->hide();t->horizontalHeader()->setStretchLastSection(true);v->addWidget(t,1);tables[i]=t;return t;}
    int selected(int i){if(!tables[i]||tables[i]->currentRow()<0)throw std::runtime_error("Select a record in the table first");return tables[i]->item(tables[i]->currentRow(),0)->text().toInt();}
    void applySearch(int i){auto*t=tables[i];if(!t)return;QString key=searches[i]?searches[i]->text().trimmed():"";QString status=filters[i]?filters[i]->currentText():"All";for(int r=0;r<t->rowCount();r++){bool match=key.isEmpty();for(int c=0;c<t->columnCount()&&!match;c++)if(t->item(r,c)&&t->item(r,c)->text().contains(key,Qt::CaseInsensitive))match=true;if(status!="All"&&status!=""&&status!="All statuses"){bool found=false;for(int c=0;c<t->columnCount();c++)if(t->item(r,c)&&t->item(r,c)->text().compare(status,Qt::CaseInsensitive)==0)found=true;match &=found;}t->setRowHidden(r,!match);}}
    void populate(int i,const QString &sql,const QVariantList &args={}){auto*q=tables[i];if(!q)return;auto result=db.query(sql,args);auto rec=result.record();q->setSortingEnabled(false);q->clear();q->setColumnCount(rec.count());QStringList headers;for(int c=0;c<rec.count();++c)headers<<rec.fieldName(c).replace('_',' ').toUpper();q->setHorizontalHeaderLabels(headers);int row=0;while(result.next()){q->insertRow(row);for(int c=0;c<rec.count();++c){auto *item=new QTableWidgetItem(result.value(c).toString());if(c==0)item->setData(Qt::UserRole,result.value(0));q->setItem(row,c,item);}row++;}q->resizeColumnsToContents();q->setSortingEnabled(true);applySearch(i);}
    void setupDashboard(QWidget *p){auto *v=new QVBoxLayout(p);v->setContentsMargins(20,20,20,20);auto*h=new QLabel("Inventory & Finance Overview");h->setObjectName("headline");v->addWidget(h);summary=new QLabel;summary->setTextFormat(Qt::RichText);summary->setWordWrap(true);v->addWidget(summary);auto *row=new QHBoxLayout;action("Refresh dashboard",[this]{refresh(0);},row);action("Insert sample data (optional)",[this]{guard([this]{if(QMessageBox::question(this,"Demo data","Add demo products, opening stock and payment accounts? This is intended for an empty database.") == QMessageBox::Yes)db.loadDemoData();});},row);action("Open database folder",[this]{QDesktopServices::openUrl(QUrl::fromLocalFile(QFileInfo(db.path()).absolutePath()));},row);row->addStretch();v->addLayout(row);auto*t=new QTableWidget;tables[0]=t;t->setEditTriggers(QAbstractItemView::NoEditTriggers);v->addWidget(new QLabel("Low-stock items by warehouse"));v->addWidget(t,1);}
    void setupTable(QWidget *p,int i){auto *v=new QVBoxLayout(p);v->setContentsMargins(14,18,14,14);auto*h=new QLabel(names[i]);h->setObjectName("headline");v->addWidget(h);auto *toolbar=new QHBoxLayout;auto*s=input();s->setPlaceholderText("Search records...");searches[i]=s;toolbar->addWidget(s,1);connect(s,&QLineEdit::textChanged,this,[this,i]{applySearch(i);});auto*filter=new QComboBox;filters[i]=filter;filter->addItem("All");if(i==3||i==4||i==5)filter->addItems({"POSTED",i==5?"VOIDED":"REVERSED"});if(i==1||i==2||i==6)filter->addItems({"Active","Archived"});toolbar->addWidget(filter);connect(filter,&QComboBox::currentTextChanged,this,[this,i]{applySearch(i);});action("Refresh",[this,i]{refresh(i);},toolbar);
        if(i==1){action("Add product",[this]{guard([this]{productForm();});},toolbar);action("Edit",[this]{guard([this]{productForm(selected(1));});},toolbar);action("Archive",[this]{guard([this]{int id=selected(1);if(QMessageBox::question(this,"Archive product","Archive selected product?")==QMessageBox::Yes)db.archiveProduct(id);});},toolbar);}
        if(i==2){action("Add warehouse",[this]{guard([this]{warehouseForm();});},toolbar);action("Edit",[this]{guard([this]{warehouseForm(selected(2));});},toolbar);action("Archive",[this]{guard([this]{int id=selected(2);if(QMessageBox::question(this,"Archive warehouse","Archive selected warehouse?")==QMessageBox::Yes)db.archiveWarehouse(id);});},toolbar);}
        if(i==3){action("New transfer",[this]{guard([this]{transferForm();});},toolbar);action("Reverse",[this]{guard([this]{int id=selected(3);if(QMessageBox::question(this,"Reverse transfer","Reverse this transfer? Destination must still have the transferred stock.")==QMessageBox::Yes)db.reverseTransfer(id);});},toolbar);}
        if(i==4){action("New adjustment",[this]{guard([this]{adjustmentForm();});},toolbar);action("Reverse",[this]{guard([this]{int id=selected(4);if(QMessageBox::question(this,"Reverse adjustment","Reverse this adjustment? Stock must remain non-negative.")==QMessageBox::Yes)db.reverseAdjustment(id);});},toolbar);}
        if(i==5){action("Add expense",[this]{guard([this]{expenseForm();});},toolbar);action("Edit",[this]{guard([this]{expenseForm(selected(5));});},toolbar);action("Void",[this]{guard([this]{int id=selected(5);if(QMessageBox::question(this,"Void expense","Void and refund this recorded expense?")==QMessageBox::Yes)db.voidExpense(id);});},toolbar);action("Categories",[this]{guard([this]{bool ok=false;QString name=QInputDialog::getText(this,"Expense category","New category name",QLineEdit::Normal,"",&ok);if(ok&&!name.trimmed().isEmpty())db.createCategory(name);});},toolbar);}
        if(i==6){action("New account",[this]{guard([this]{accountForm();});},toolbar);action("Edit",[this]{guard([this]{accountForm(selected(6));});},toolbar);action("Deposit / Withdraw",[this]{guard([this]{cashForm();});},toolbar);action("Transfer funds",[this]{guard([this]{fundsForm();});},toolbar);action("Reverse funds",[this]{guard([this]{bool ok=false;int id=QInputDialog::getInt(this,"Reverse funds transfer","Transfer ID (see Reports → Funds transfers):",1,1,100000000,1,&ok);if(ok && QMessageBox::question(this,"Reverse funds","Reverse posted funds transfer #"+QString::number(id)+"?")==QMessageBox::Yes)db.reverseFundsTransfer(id);});},toolbar);action("Archive",[this]{guard([this]{int id=selected(6);if(QMessageBox::question(this,"Archive account","Account must have a zero balance. Continue?")==QMessageBox::Yes)db.archiveAccount(id);});},toolbar);}
        v->addLayout(toolbar);makeTable(p,v,i);auto*foot=new QLabel("Posted transactions are preserved for audit. Use Reverse/Void instead of deleting historical transactions.");foot->setStyleSheet("color:#68798b");v->addWidget(foot);
    }
    void productForm(int id=0){QStringList values; if(id){auto q=db.query("SELECT sku,name,category,unit,cost_cents,price_cents,min_stock FROM products WHERE id=?",{id});if(!q.next())throw std::runtime_error("Product not found");for(int k=0;k<7;k++)values<<q.value(k).toString();}QDialog d(this);auto*f=new QFormLayout;auto sku=input(id?values[0]:"");auto name=input(id?values[1]:"");auto cat=input(id?values[2]:"General");auto unit=input(id?values[3]:"pcs");auto cost=number(id?values[4].toDouble()/100:0);auto price=number(id?values[5].toDouble()/100:0);auto min=number(id?values[6].toDouble():0,false,3);f->addRow("SKU *",sku);f->addRow("Product name *",name);f->addRow("Category",cat);f->addRow("Unit",unit);f->addRow("Purchase cost",cost);f->addRow("Selling price",price);f->addRow("Minimum stock",min);if(showForm(this,id?"Edit product":"Add product",f,d)){if(id)db.editProduct(id,sku->text(),name->text(),cat->text(),unit->text(),cents(cost->value()),cents(price->value()),min->value());else db.createProduct(sku->text(),name->text(),cat->text(),unit->text(),cents(cost->value()),cents(price->value()),min->value());}}
    void warehouseForm(int id=0){QString n,c;if(id){auto q=db.query("SELECT name,code FROM warehouses WHERE id=?",{id});if(!q.next())throw std::runtime_error("Warehouse not found");n=q.value(0).toString();c=q.value(1).toString();}QDialog d(this);auto*f=new QFormLayout;auto name=input(n); auto code=input(c);f->addRow("Name *",name);f->addRow("Code *",code);if(showForm(this,id?"Edit warehouse":"New warehouse",f,d)){if(id)db.editWarehouse(id,name->text(),code->text());else db.createWarehouse(name->text(),code->text());}}
    void transferForm(){QDialog d(this);auto*f=new QFormLayout;auto from=lookup(db,"SELECT id,name FROM warehouses WHERE active=1"); auto to=lookup(db,"SELECT id,name FROM warehouses WHERE active=1");auto prod=lookup(db,"SELECT id,sku || ' - ' || name FROM products WHERE active=1");auto qty=number(1,false,3);auto note=input();f->addRow("From warehouse",from);f->addRow("To warehouse",to);f->addRow("Product",prod);f->addRow("Quantity",qty);f->addRow("Note",note);auto *help=new QLabel("Create one transfer per product. Each posted transfer updates both warehouses atomically.");help->setWordWrap(true);f->addRow(help);if(showForm(this,"New stock transfer",f,d)){if(from->count()==0||to->count()==0||prod->count()==0)throw std::runtime_error("Create warehouses and products first");db.postTransfer(from->currentData().toInt(),to->currentData().toInt(),{{prod->currentData().toInt(),qty->value()}},note->text());}}
    void adjustmentForm(){QDialog d(this);auto*f=new QFormLayout;auto wh=lookup(db,"SELECT id,name FROM warehouses WHERE active=1"); auto prod=lookup(db,"SELECT id,sku || ' - ' || name FROM products WHERE active=1");auto qty=number(0,true,3);auto reason=new QComboBox;reason->addItems({"Opening stock","Damage / loss","Stock count correction","Purchase / receipt","Customer return","Other"});auto note=input();auto available=new QLabel("Select a product and warehouse");auto update=[this,wh,prod,available]{if(wh->count()&&prod->count())available->setText("Current stock: " +quantity(db.stockAt(wh->currentData().toInt(),prod->currentData().toInt())));};connect(wh,&QComboBox::currentIndexChanged,&d,[update](int){update();});connect(prod,&QComboBox::currentIndexChanged,&d,[update](int){update();});update();f->addRow("Warehouse",wh);f->addRow("Product",prod);f->addRow(available);f->addRow("Adjustment (+/-)",qty);f->addRow("Reason",reason);f->addRow("Notes",note);if(showForm(this,"Stock adjustment",f,d)){if(!wh->count()||!prod->count())throw std::runtime_error("Create warehouses and products first");db.postAdjustment(wh->currentData().toInt(),reason->currentText(),{{prod->currentData().toInt(),qty->value()}},note->text());}}
    void expenseForm(int id=0){QDate date=QDate::currentDate();int oldCat=0,oldAccount=0;qint64 oldAmount=0;QString desc,note;if(id){auto q=db.query("SELECT expense_date,category_id,account_id,description,amount_cents,note FROM expenses WHERE id=?",{id});if(!q.next())throw std::runtime_error("Expense missing");date=QDate::fromString(q.value(0).toString(),Qt::ISODate);oldCat=q.value(1).toInt();oldAccount=q.value(2).toInt();desc=q.value(3).toString();oldAmount=q.value(4).toLongLong();note=q.value(5).toString();}QDialog d(this);auto*f=new QFormLayout;auto day=new QDateEdit(date);day->setCalendarPopup(true);auto cat=lookup(db,"SELECT id,name FROM expense_categories WHERE active=1"); auto acc=lookup(db,"SELECT id,name FROM payment_accounts WHERE active=1");selectId(cat,oldCat);selectId(acc,oldAccount);auto description=input(desc);auto amount=number(oldAmount/100.0);auto extra=input(note);f->addRow("Date",day);f->addRow("Category",cat);f->addRow("Paid from",acc);f->addRow("Description *",description);f->addRow("Amount *",amount);f->addRow("Notes",extra);if(showForm(this,id?"Edit expense":"Add expense",f,d)){if(!cat->count()||!acc->count())throw std::runtime_error("Create an active payment account and expense category first");if(id)db.editExpense(id,day->date(),cat->currentData().toInt(),acc->currentData().toInt(),description->text(),cents(amount->value()),extra->text());else db.addExpense(day->date(),cat->currentData().toInt(),acc->currentData().toInt(),description->text(),cents(amount->value()),extra->text());}}
    void accountForm(int id=0){QString n,k; if(id){auto q=db.query("SELECT name,kind FROM payment_accounts WHERE id=?",{id});if(!q.next())throw std::runtime_error("Account missing");n=q.value(0).toString();k=q.value(1).toString();}QDialog d(this);auto*f=new QFormLayout;auto name=input(n);auto kind=new QComboBox;kind->addItems({"Cash","Bank","Mobile Banking","Card Clearing","Other"});if(!k.isEmpty())kind->setCurrentText(k);auto opening=number();f->addRow("Account name *",name);f->addRow("Account type",kind);if(!id)f->addRow("Opening balance",opening);if(showForm(this,id?"Edit account":"New payment account",f,d)){if(id)db.editAccount(id,name->text(),kind->currentText());else db.createAccount(name->text(),kind->currentText(),cents(opening->value()));}}
    void cashForm(){QDialog d(this);auto*f=new QFormLayout;auto acc=lookup(db,"SELECT id,name FROM payment_accounts WHERE active=1");auto type=new QComboBox;type->addItems({"Deposit","Withdrawal"});auto amount=number();auto note=input();f->addRow("Account",acc);f->addRow("Action",type);f->addRow("Amount",amount);f->addRow("Description *",note);if(showForm(this,"Deposit / withdrawal",f,d)){if(!acc->count())throw std::runtime_error("Create a payment account first");auto a=cents(amount->value());db.depositOrWithdraw(acc->currentData().toInt(),type->currentIndex()==0?a:-a,note->text());}}
    void fundsForm(){QDialog d(this);auto*f=new QFormLayout;auto from=lookup(db,"SELECT id,name FROM payment_accounts WHERE active=1"); auto to=lookup(db,"SELECT id,name FROM payment_accounts WHERE active=1");auto amount=number();auto note=input();f->addRow("From account",from);f->addRow("To account",to);f->addRow("Amount",amount);f->addRow("Notes",note);if(showForm(this,"Transfer between accounts",f,d)){if(!from->count()||!to->count())throw std::runtime_error("Create two accounts first");db.transferFunds(from->currentData().toInt(),to->currentData().toInt(),cents(amount->value()),note->text());}}
    QComboBox *reportChoice=nullptr;QDateEdit *dateFrom=nullptr,*dateTo=nullptr;QTableWidget *reportTable=nullptr;
    void setupReports(QWidget *p){auto*v=new QVBoxLayout(p);v->setContentsMargins(18,18,18,18);auto *h=new QLabel("Reports & Data Analysis");h->setObjectName("headline");v->addWidget(h);auto *bar=new QHBoxLayout;reportChoice=new QComboBox;reportChoice->addItems({"Stock by warehouse","Stock valuation","Low stock alerts","Stock movement audit","Transfers","Adjustments","Expenses by category","Expenses detail","Account balances","Account ledger","Funds transfers","Monthly expenses"});bar->addWidget(reportChoice,2);dateFrom=new QDateEdit(QDate::currentDate().addMonths(-1));dateFrom->setCalendarPopup(true);dateTo=new QDateEdit(QDate::currentDate());dateTo->setCalendarPopup(true);bar->addWidget(new QLabel("From:"));bar->addWidget(dateFrom);bar->addWidget(new QLabel("To:"));bar->addWidget(dateTo);action("Generate",[this]{guard([this]{generateReport();});},bar);action("Export visible CSV",[this]{exportCsv();},bar);v->addLayout(bar);reportTable=new QTableWidget;reportTable->setAlternatingRowColors(true);reportTable->setEditTriggers(QAbstractItemView::NoEditTriggers);reportTable->verticalHeader()->hide();reportTable->horizontalHeader()->setStretchLastSection(true);v->addWidget(reportTable,1);connect(reportChoice,&QComboBox::currentIndexChanged,this,[this]{guard([this]{generateReport();});});}
    void reportPopulate(const QString &sql,const QVariantList &params={}){auto q=db.query(sql,params);auto rec=q.record();reportTable->clear();reportTable->setRowCount(0);reportTable->setColumnCount(rec.count());QStringList headers;for(int i=0;i<rec.count();++i)headers<<rec.fieldName(i).replace('_',' ').toUpper();reportTable->setHorizontalHeaderLabels(headers);int r=0;while(q.next()){reportTable->insertRow(r);for(int c=0;c<rec.count();c++)reportTable->setItem(r,c,new QTableWidgetItem(q.value(c).toString()));r++;}reportTable->resizeColumnsToContents();}
    void generateReport(){if(dateFrom->date()>dateTo->date())throw std::runtime_error("From date must not be later than To date");QString f=dateFrom->date().toString(Qt::ISODate),t=dateTo->date().toString(Qt::ISODate);switch(reportChoice->currentIndex()){
        case 0:reportPopulate("SELECT w.name warehouse,p.sku,p.name product,ROUND(s.qty,3) qty,p.unit FROM stock s JOIN warehouses w ON w.id=s.warehouse_id JOIN products p ON p.id=s.product_id ORDER BY w.name,p.name");break;
        case 1:reportPopulate("SELECT w.name warehouse,p.sku,p.name product,ROUND(s.qty,3) qty,printf('%.2f',p.cost_cents/100.0) unit_cost,printf('%.2f',s.qty*p.cost_cents/100.0) stock_value FROM stock s JOIN warehouses w ON w.id=s.warehouse_id JOIN products p ON p.id=s.product_id ORDER BY w.name,p.name");break;
        case 2:reportPopulate("SELECT w.name warehouse,p.sku,p.name product,ROUND(COALESCE(s.qty,0),3) on_hand,p.min_stock minimum FROM warehouses w CROSS JOIN products p LEFT JOIN stock s ON s.warehouse_id=w.id AND s.product_id=p.id WHERE w.active=1 AND p.active=1 AND COALESCE(s.qty,0)<p.min_stock ORDER BY w.name,p.name");break;
        case 3:reportPopulate("SELECT substr(e.occurred_at,1,19) date,e.kind,p.sku,w.name warehouse,e.delta,e.document_id FROM stock_events e JOIN products p ON p.id=e.product_id JOIN warehouses w ON w.id=e.warehouse_id WHERE substr(e.occurred_at,1,10) BETWEEN ? AND ? ORDER BY e.id DESC",{f,t});break;
        case 4:reportPopulate("SELECT t.reference,substr(t.occurred_at,1,19) date,a.name source,b.name destination,p.sku,l.qty,t.status,t.note FROM stock_transfers t JOIN stock_transfer_lines l ON l.transfer_id=t.id JOIN products p ON p.id=l.product_id JOIN warehouses a ON a.id=t.from_warehouse JOIN warehouses b ON b.id=t.to_warehouse WHERE substr(t.occurred_at,1,10) BETWEEN ? AND ? ORDER BY t.id DESC",{f,t});break;
        case 5:reportPopulate("SELECT a.reference,substr(a.occurred_at,1,19) date,w.name warehouse,p.sku,l.delta,a.reason,a.status FROM stock_adjustments a JOIN stock_adjustment_lines l ON l.adjustment_id=a.id JOIN products p ON p.id=l.product_id JOIN warehouses w ON w.id=a.warehouse_id WHERE substr(a.occurred_at,1,10) BETWEEN ? AND ? ORDER BY a.id DESC",{f,t});break;
        case 6:reportPopulate("SELECT c.name category,COUNT(*) transactions,printf('%.2f',SUM(e.amount_cents)/100.0) total_expense FROM expenses e JOIN expense_categories c ON c.id=e.category_id WHERE e.status='POSTED' AND e.expense_date BETWEEN ? AND ? GROUP BY c.id ORDER BY SUM(e.amount_cents) DESC",{f,t});break;
        case 7:reportPopulate("SELECT e.expense_date date,c.name category,a.name account,e.description,printf('%.2f',e.amount_cents/100.0) amount,e.status,e.note FROM expenses e JOIN expense_categories c ON c.id=e.category_id JOIN payment_accounts a ON a.id=e.account_id WHERE e.expense_date BETWEEN ? AND ? ORDER BY e.expense_date DESC,e.id DESC",{f,t});break;
        case 8:reportPopulate("SELECT a.name account,a.kind type,a.active,printf('%.2f',COALESCE(SUM(m.amount_cents),0)/100.0) balance FROM payment_accounts a LEFT JOIN account_movements m ON m.account_id=a.id GROUP BY a.id ORDER BY a.name");break;
        case 9:reportPopulate("SELECT substr(m.occurred_at,1,19) date,a.name account,m.kind,printf('%.2f',m.amount_cents/100.0) amount,m.document_id,m.description FROM account_movements m JOIN payment_accounts a ON a.id=m.account_id WHERE substr(m.occurred_at,1,10) BETWEEN ? AND ? ORDER BY m.id DESC",{f,t});break;
        case 10:reportPopulate("SELECT t.id,substr(t.occurred_at,1,19) date,a.name source,b.name destination,printf('%.2f',t.amount_cents/100.0) amount,t.status,t.note FROM account_transfers t JOIN payment_accounts a ON a.id=t.from_account JOIN payment_accounts b ON b.id=t.to_account WHERE substr(t.occurred_at,1,10) BETWEEN ? AND ? ORDER BY t.id DESC",{f,t});break;
        case 11:reportPopulate("SELECT substr(expense_date,1,7) month,COUNT(*) expenses,printf('%.2f',SUM(amount_cents)/100.0) total FROM expenses WHERE status='POSTED' AND expense_date BETWEEN ? AND ? GROUP BY substr(expense_date,1,7) ORDER BY month",{f,t});break;
    }}
    void exportCsv(){if(!reportTable||!reportTable->rowCount()){QMessageBox::information(this,"No data","Generate a report with rows before exporting.");return;}QString filename=QFileDialog::getSaveFileName(this,"Export report","japan365pos_report.csv","CSV files (*.csv)");if(filename.isEmpty())return;QFile file(filename);if(!file.open(QIODevice::WriteOnly|QIODevice::Text)){QMessageBox::warning(this,"Export failed",file.errorString());return;}QTextStream out(&file);out.setEncoding(QStringConverter::Utf8);auto escape=[](QString s){s.replace('"',"\"\"");return "\""+s+"\"";};QStringList header;for(int c=0;c<reportTable->columnCount();c++)header<<escape(reportTable->horizontalHeaderItem(c)->text());out<<header.join(',')<<'\n';for(int r=0;r<reportTable->rowCount();r++){QStringList row;for(int c=0;c<reportTable->columnCount();c++)row<<escape(reportTable->item(r,c)?reportTable->item(r,c)->text():"");out<<row.join(',')<<'\n';}QMessageBox::information(this,"Export complete","Saved: "+filename);}
    void refresh(int i){if(i==0){qint64 value=db.scalar("SELECT COALESCE(SUM(s.qty*p.cost_cents),0) FROM stock s JOIN products p ON p.id=s.product_id").toLongLong();qint64 cash=db.scalar("SELECT COALESCE(SUM(amount_cents),0) FROM account_movements").toLongLong();qint64 expense=db.scalar("SELECT COALESCE(SUM(amount_cents),0) FROM expenses WHERE status='POSTED'").toLongLong();int products=db.scalar("SELECT COUNT(*) FROM products WHERE active=1").toInt();summary->setText(QString("<div style='font-size:16px;line-height:220%%'><b>Stock valuation:</b> %1 BDT &nbsp;&nbsp;&nbsp; <b>Payment balances:</b> %2 BDT &nbsp;&nbsp;&nbsp; <b>Recorded expenses:</b> %3 BDT &nbsp;&nbsp;&nbsp; <b>Active products:</b> %4</div>").arg(money(value),money(cash),money(expense),QString::number(products)));auto q=db.query("SELECT w.name,p.sku,p.name,ROUND(COALESCE(s.qty,0),3),p.min_stock FROM warehouses w CROSS JOIN products p LEFT JOIN stock s ON s.warehouse_id=w.id AND s.product_id=p.id WHERE w.active=1 AND p.active=1 AND COALESCE(s.qty,0)<p.min_stock ORDER BY w.name,p.name");auto*t=tables[0];t->clear();t->setRowCount(0);t->setColumnCount(5);t->setHorizontalHeaderLabels({"Warehouse","SKU","Product","Available","Minimum"});int r=0;while(q.next()){t->insertRow(r);for(int c=0;c<5;c++)t->setItem(r,c,new QTableWidgetItem(q.value(c).toString()));r++;}t->horizontalHeader()->setStretchLastSection(true);return;}
        if(i==1)populate(i,"SELECT id,sku,name,category,unit,printf('%.2f',cost_cents/100.0) cost,printf('%.2f',price_cents/100.0) price,min_stock,CASE WHEN active=1 THEN 'Active' ELSE 'Archived' END status FROM products ORDER BY id DESC");
        if(i==2)populate(i,"SELECT id,name,code,CASE WHEN active=1 THEN 'Active' ELSE 'Archived' END status FROM warehouses ORDER BY id DESC");
        if(i==3)populate(i,"SELECT t.id,t.reference,substr(t.occurred_at,1,19) date,a.name source,b.name destination,COUNT(l.id) product_lines,ROUND(SUM(l.qty),3) total_units,t.status,t.note FROM stock_transfers t JOIN warehouses a ON a.id=t.from_warehouse JOIN warehouses b ON b.id=t.to_warehouse JOIN stock_transfer_lines l ON l.transfer_id=t.id GROUP BY t.id ORDER BY t.id DESC");
        if(i==4)populate(i,"SELECT a.id,a.reference,substr(a.occurred_at,1,19) date,w.name warehouse,a.reason,COUNT(l.id) product_lines,ROUND(SUM(l.delta),3) net_units,a.status,a.note FROM stock_adjustments a JOIN warehouses w ON w.id=a.warehouse_id JOIN stock_adjustment_lines l ON l.adjustment_id=a.id GROUP BY a.id ORDER BY a.id DESC");
        if(i==5)populate(i,"SELECT e.id,e.expense_date date,c.name category,a.name account,e.description,printf('%.2f',e.amount_cents/100.0) amount,e.status,e.note FROM expenses e JOIN expense_categories c ON c.id=e.category_id JOIN payment_accounts a ON a.id=e.account_id ORDER BY e.id DESC");
        if(i==6)populate(i,"SELECT a.id,a.name,a.kind,printf('%.2f',COALESCE(SUM(m.amount_cents),0)/100.0) balance,CASE WHEN a.active=1 THEN 'Active' ELSE 'Archived' END status FROM payment_accounts a LEFT JOIN account_movements m ON m.account_id=a.id GROUP BY a.id ORDER BY a.id DESC");
        if(i==7)generateReport();
    }
};
int main(int argc,char *argv[]){QApplication app(argc,argv);app.setApplicationName("Japan 365 POS");app.setApplicationDisplayName("Japan 365 POS");app.setOrganizationName("Japan365POS");try{Japan365Window w;w.show();return app.exec();}catch(const std::exception &e){QMessageBox::critical(nullptr,"Startup failed",QString::fromUtf8(e.what()));return 1;}}
